trigger:
  branches:
    include:
      - main

variables:
  acrServiceConnection: 'acr-jav-service'
  azureSubscription: 'acr-java-connection'
  imageRepository: 'student-javaproject'
  containerRegistry: 'acrjavapoject.azurecr.io'
  aksResourceGroup: 'rg-javaproject'
  aksClusterName: 'aks-java'
  imageTag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build & Push Image

  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: Dockerfile
        containerRegistry: $(acrServiceConnection)
        tags: |
          $(imageTag)

    - task: PublishPipelineArtifact@1
      displayName: Publish Kubernetes Manifests
      inputs:
        targetPath: 'k8s'
        artifact: manifests

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: Deploy to AKS

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - download: current
      artifact: manifests

    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: deploy
        kubernetesServiceConnection: 'aks-java-connection'
        namespace: default
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yaml
          $(Pipeline.Workspace)/manifests/service.yaml
        containers: |
          $(containerRegistry)/$(imageRepository):$(imageTag)
