version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: studenthub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  studenthub:
    build: .
    container_name: studenthub-app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8000:8000"

volumes:
  mysql_data:
