apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentjava
  template:
    metadata:
      labels:
        app: studentjava
    spec:
      containers:
      - name: studentjava
        image: yashuraj/javapjt:latest
        ports:
        - containerPort: 8002
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
