apiVersion: apps/v1
kind: Deployment
metadata:
  name: studenthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studenthub
  template:
    metadata:
      labels:
        app: studenthub
    spec:
      containers:
      - name: studenthub
        image: akshithavarkala/studenthub-java-studenthub
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
